//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Email = new HashSet<Email>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime Purschace { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string Expectations { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Pending { get; set; }
        public Nullable<System.DateTime> InProgress { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> AppType_Id { get; set; }
        public Nullable<int> Realization_Id { get; set; }
        public Nullable<int> Statue_Id { get; set; }
        public Nullable<int> Result_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
    
        public virtual AppType AppType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Realization Realization { get; set; }
        public virtual Result Result { get; set; }
        public virtual Statue Statue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Email { get; set; }
    }
}
