//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICATION()
        {
            this.EMAIL = new HashSet<EMAIL>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string INVOICENO { get; set; }
        public System.DateTime DATEPURSCHASE { get; set; }
        public string CONTENT { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXPECTATIONS { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> DATASTART { get; set; }
        public Nullable<System.DateTime> PENDING { get; set; }
        public Nullable<System.DateTime> INPROGRESS { get; set; }
        public Nullable<System.DateTime> ENDSTART { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> APPTYPE_ID { get; set; }
        public Nullable<int> REALIZATION_ID { get; set; }
        public Nullable<int> STATUE_ID { get; set; }
        public Nullable<int> RESULT_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
    
        public virtual APPTYPE APPTYPE { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual REALIZATION REALIZATION { get; set; }
        public virtual RESULT RESULT { get; set; }
        public virtual STATUE STATUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL> EMAIL { get; set; }
    }
}
