//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using RMASystem.Validator;

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Email = new HashSet<Email>();
        }
		
        public int Id { get; set; }

		[Display(Name = "Kod")]
		public string Name { get; set; }

		[Required]
		[Display(Name = "Nr Faktury")]	
		public string InvoiceNo { get; set; }

		[Required]
		[DataType(DataType.Date)]
		[Display(Name = "Data zakupu")]
		[NotFutureDate]
		public System.DateTime Purschace { get; set; }

		[Required]
		[Display(Name = "Zawartość")]
		[DataType(DataType.MultilineText)]
		[StringLength(255, MinimumLength = 10)]
		public string Content { get; set; }

		[Required]
		[Display(Name = "Opis")]
		[DataType(DataType.MultilineText)]
		[StringLength(255, MinimumLength = 20)]
		public string Description { get; set; }

		[Display(Name = "Oczekiwania")]
		[DataType(DataType.MultilineText)]
		[StringLength(255, MinimumLength = 10)]
		public string Expectations { get; set; }

		[Range(0, 9999999.99)]
		public Nullable<decimal> Cost { get; set; }

		[DataType(DataType.Date, ErrorMessage = "Data musi miec format ")]
		[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
		[Display(Name = "Data otwarcia")]
		[NotFutureDate]
		public Nullable<System.DateTime> Start { get; set; }

		[DataType(DataType.Date, ErrorMessage = "Data musi miec format dd-mm-rrrr")]
		[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
		[Display(Name = "Data oczekiwania")]
		[NotFutureDate]
		public Nullable<System.DateTime> Pending { get; set; }

		[DataType(DataType.Date, ErrorMessage = "Data musi miec format dd-mm-rrrr")]
		[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
		[Display(Name = "Data realizacji")]
		[NotFutureDate]
		public Nullable<System.DateTime> InProgress { get; set; }

		[DataType(DataType.Date, ErrorMessage = "Data musi miec format dd-mm-rrrr")]
		[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
		[Display(Name = "Data zakończenia")]
		[NotFutureDate]
		public Nullable<System.DateTime> End { get; set; }

		[Required]
		[Display(Name = "Produkt")]
        public Nullable<int> Product_Id { get; set; }

		[Required]
		[Display(Name = "Typ zlecenia")]
        public Nullable<int> AppType_Id { get; set; }

		[Required]
		[Display(Name = "Sposób realizacji")]
		public Nullable<int> Realization_Id { get; set; }
        public Nullable<int> Statue_Id { get; set; }
        public Nullable<int> Result_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
    
        public virtual AppType AppType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Realization Realization { get; set; }
        public virtual Result Result { get; set; }
        public virtual Statue Statue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Email { get; set; }

    }
}
