//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }

		[Required]
		[Display(Name = "Nazwa banku")]
        public string Name { get; set; }

		[Required]
		[Display(Name = "Numer konta")]
		[StringLength(26, MinimumLength = 26, ErrorMessage = "Konto bankowe musi miec 26 cyfr.")]
		[RegularExpression("^[0-9]*$", ErrorMessage = "Tylko cyfry są dozwolone.")]
		public string AccountNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
