//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }

		[Required]
		[Display(Name = "Nadawca")]
		public string Sender { get; set; }

		[Required]
		[Display(Name = "Odbiorca")]
		public string Reciper { get; set; }

		[Required]
		[Display(Name = "Temat")]
		public string Subject { get; set; }

		[Display(Name = "Treœæ")]
		public string Content { get; set; }

        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> Application_Id { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
