//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMASystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMAEntities : DbContext
    {
        public RMAEntities()
            : base("name=RMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRESS> ADRESS { get; set; }
        public virtual DbSet<APPLICATION> APPLICATION { get; set; }
        public virtual DbSet<APPTYPE> APPTYPE { get; set; }
        public virtual DbSet<BANKACCOUNT> BANKACCOUNT { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<EMAIL> EMAIL { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<REALIZATION> REALIZATION { get; set; }
        public virtual DbSet<RESULT> RESULT { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<STATUE> STATUE { get; set; }
    }
}
