//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMASystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RmaEntities : DbContext
    {
        public RmaEntities()
            : base("name=RmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<AppType> AppType { get; set; }
        public virtual DbSet<BankAccount> BankAccount { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Realization> Realization { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Statue> Statue { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
