//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Application = new HashSet<Application>();
            this.Application1 = new HashSet<Application>();
        }
    
        public int Id { get; set; }

		[Required]
		[Display(Name = "Imie")]
		[RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Dozwolone są tylko litery")]
		[StringLength(30, MinimumLength = 2)]
		public string FirstName { get; set; }

		[Required]
		[Display(Name = "Nazwisko")]
		[RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Dozwolone są tylko litery")]
		[StringLength(40, MinimumLength = 2)]
		public string LastName { get; set; }

		[Required]
		[Display(Name = "Telefon")]
		[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{3})$", ErrorMessage = "Telefon musi być w formacie 123-456-789.")]
		[StringLength(20, MinimumLength = 9)]
        public string Phone { get; set; }

		[Required]
		[Display(Name = "E-mail")]
		[EmailAddress(ErrorMessage = "Niepoprawny adres e-mail.")]
		public string Email { get; set; }

		[Required]
		[Display(Name = "Hasło")]
		[DataType(DataType.Password)]
		[StringLength(30, MinimumLength = 8)]
		public string Password { get; set; }

		[Required]
		[Display(Name = "Rola")]
		public Nullable<int> Role_Id { get; set; }

		[Display(Name = "Adres")]
		public Nullable<int> Adress_Id { get; set; }

		[Display(Name = "Konto bankowe")]
		public Nullable<int> BankAccount_Id { get; set; }

	    public string FullName => $"{FirstName} {LastName}";

		public virtual Adress Adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application1 { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Role Role { get; set; }
    }
}
