//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMASystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Application = new HashSet<Application>();
            this.Application1 = new HashSet<Application>();
        }
    
        public int Id { get; set; }
		[Required]
		[StringLength(30)]
		public string FirstName { get; set; }
		[Required]
		[StringLength(40)]
		public string LastName { get; set; }
		[Required]
		[StringLength(20)]
        public string Phone { get; set; }
		[Required]
		public string Email { get; set; }
		[Required]
		public string Password { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Adress_Id { get; set; }
        public Nullable<int> BankAccount_Id { get; set; }
	    public string FullName => $"{FirstName} {LastName}";

		public virtual Adress Adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application1 { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Role Role { get; set; }
    }
}
